---
- name: if postgres is already installed
  stat:
    path: /usr/bin/postgres
  register: postgres_bin

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: initilize postgres
  when: not postgres_bin.stat.exists
  command: postgresql-setup initdb

- name: initilize postgres some more
  when: not postgres_bin.stat.exists
  command: chkconfig postgresql on

- name: start postgres
  service:
    name: postgresql.service
    state: started
